nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            schemas:
                Message:
                    properties:
                        distance:
                            type: float
                            example: 1789.2,
                        message:
                            ref: "#/components/schemas/message_basic"
                mess:
                    properties:
                        id:
                            type: integer
                            example: 123
                        text:
                            type: string
                            example: "The message text!"
                        date:
                            type: string
                            example: "2020-01-01 00:00:00"
                address:
                    properties:
                        text:
                            type: string
                            example: "coucou"
                        address:
                            type: string
                            example: "123 av Paris"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        names:
            - { alias: message_basic, type: App\Entity\Message, groups: [message_basic]}
            - { alias: user_basic, type: App\Entity\User, groups: [user_basic]}
        

        