nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            schemas:
                Message:
                    description: "Response for some queries"
                    type: object
                    properties:
                        distance:
                            type: float
                            example: 1789.2,
                        message:
                            type: array
                            items:
                                $ref: "#/components/schemas/"
                mess:
                    properties:
                        id:
                            type: integer
                            example: 123
                        text:
                            type: string
                            example: "The message text!"
                        date:
                            type: string
                            example: "2020-01-01 00:00:00"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

        